### ISSUE TITLE
Failed to open the installed app after update

### ISSUE THREAD

**Issue by ashishBharadwaj** [mikehardy/react-native-update-apk#25]
Getting react native version mismatch error once I try to open the installed app after update.

![image](https://user-images.githubusercontent.com/8766201/76250760-df8ffe00-626b-11ea-9951-add9fe4993d2.png)

**Comment by mikehardy** [comment]
You must read the App.js source code as it is the implementation template you will want to start with at least

And you should read the alert that popped up

https://github.com/mikehardy/react-native-update-apk/blob/master/example/App.js#L51

This gets me frequently when working on the module itself, which is why I added the popup :-)

**Comment by ashishBharadwaj** [comment]
@mikehardy : I am trying to implement this into my code and this is how I m trying to pass value to apkVersionURL:
![image](https://user-images.githubusercontent.com/8766201/76396991-4c0c1980-63a0-11ea-80cb-f1006040aaf7.png)
But getting Network error . Could you help me understand what am I doing wrong here
![image](https://user-images.githubusercontent.com/8766201/76396793-dd2ec080-639f-11ea-80d0-999d8a5fc54c.png)
